//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: integral
// ----------------------------------------------------------------------------
pub mod integral {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for integral
    pub fn program_id() -> Pubkey {
        pubkey!("9Ay66qfjtXeHJwNDZkoko11zcnojQBsuqatwA4J8FpgJ")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: SettleMarket
    // ....................................................................

    /// Main instruction struct for SettleMarket
    pub struct SettleMarketInstruction {
        pub accounts: SettleMarketInstructionAccountMetas,
        pub data: SettleMarketInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SettleMarket instruction
    #[derive(Debug, Clone, Default)]
    pub struct SettleMarketInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub mint: AccountMeta,
    }

    /// Account pubkeys for SettleMarket instruction
    #[derive(Debug, Clone)]
    pub struct SettleMarketInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub mint: Pubkey,
    }

    impl SettleMarketInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, market: Pubkey, mint: Pubkey) -> Self {
            Self {
                authority,

                config,

                market,

                mint,
            }
        }
    }

    /// Instruction data for SettleMarket
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SettleMarketInstructionData {
        pub status: MarketStatus,
    }

    impl SettleMarketInstructionData {
        pub fn new(status: MarketStatus) -> Self {
            Self { status }
        }
    }

    /// Implementation for SettleMarketInstruction
    impl SettleMarketInstruction {
        fn discriminator() -> [u8; 8] {
            [50u8, 8u8, 233u8, 142u8, 128u8, 156u8, 229u8, 84u8]
        }

        pub fn data(data: SettleMarketInstructionData) -> Self {
            Self {
                accounts: SettleMarketInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SettleMarketInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.market = AccountMeta::new(accounts.market, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.mint.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: AddRewards
    // ....................................................................

    /// Main instruction struct for AddRewards
    pub struct AddRewardsInstruction {
        pub accounts: AddRewardsInstructionAccountMetas,
        pub data: AddRewardsInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddRewards instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddRewardsInstructionAccountMetas {
        pub signer: AccountMeta,

        pub config: AccountMeta,

        pub reward_mint: AccountMeta,

        pub signer_ata: AccountMeta,

        pub reward_vault: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for AddRewards instruction
    #[derive(Debug, Clone)]
    pub struct AddRewardsInstructionAccounts {
        pub signer: Pubkey,

        pub config: Pubkey,

        pub reward_mint: Pubkey,

        pub signer_ata: Pubkey,

        pub reward_vault: Pubkey,
    }

    impl AddRewardsInstructionAccounts {
        pub fn new(
            signer: Pubkey,

            config: Pubkey,

            reward_mint: Pubkey,

            signer_ata: Pubkey,

            reward_vault: Pubkey,
        ) -> Self {
            Self {
                signer,

                config,

                reward_mint,

                signer_ata,

                reward_vault,
            }
        }
    }

    /// Instruction data for AddRewards
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddRewardsInstructionData {
        pub amount: u64,
    }

    impl AddRewardsInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for AddRewardsInstruction
    impl AddRewardsInstruction {
        fn discriminator() -> [u8; 8] {
            [88u8, 186u8, 25u8, 227u8, 38u8, 137u8, 81u8, 23u8]
        }

        pub fn data(data: AddRewardsInstructionData) -> Self {
            Self {
                accounts: AddRewardsInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddRewardsInstructionAccounts) -> Self {
            self.accounts.signer = AccountMeta::new(accounts.signer, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.reward_mint = AccountMeta::new_readonly(accounts.reward_mint, false);

            self.accounts.signer_ata = AccountMeta::new(accounts.signer_ata, false);

            self.accounts.reward_vault = AccountMeta::new(accounts.reward_vault, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.signer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.reward_mint.clone());

            metas.push(self.accounts.signer_ata.clone());

            metas.push(self.accounts.reward_vault.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ClaimFees
    // ....................................................................

    /// Main instruction struct for ClaimFees
    pub struct ClaimFeesInstruction {
        pub accounts: ClaimFeesInstructionAccountMetas,
        pub data: ClaimFeesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ClaimFees instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimFeesInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub mint: AccountMeta,

        pub vault: AccountMeta,

        pub authority_ata: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for ClaimFees instruction
    #[derive(Debug, Clone)]
    pub struct ClaimFeesInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub mint: Pubkey,

        pub vault: Pubkey,

        pub authority_ata: Pubkey,
    }

    impl ClaimFeesInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            market: Pubkey,

            mint: Pubkey,

            vault: Pubkey,

            authority_ata: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                market,

                mint,

                vault,

                authority_ata,
            }
        }
    }

    /// Instruction data for ClaimFees
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimFeesInstructionData {}

    impl ClaimFeesInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ClaimFeesInstruction
    impl ClaimFeesInstruction {
        fn discriminator() -> [u8; 8] {
            [82u8, 251u8, 233u8, 156u8, 12u8, 52u8, 184u8, 202u8]
        }

        pub fn data(data: ClaimFeesInstructionData) -> Self {
            Self {
                accounts: ClaimFeesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimFeesInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new(accounts.market, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.authority_ata = AccountMeta::new(accounts.authority_ata, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.authority_ata.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ClaimRewards
    // ....................................................................

    /// Main instruction struct for ClaimRewards
    pub struct ClaimRewardsInstruction {
        pub accounts: ClaimRewardsInstructionAccountMetas,
        pub data: ClaimRewardsInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ClaimRewards instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimRewardsInstructionAccountMetas {
        pub farmer: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub reward_mint: AccountMeta,

        pub mint: AccountMeta,

        pub receipt_mint: AccountMeta,

        pub reward_vault: AccountMeta,

        pub vault: AccountMeta,

        pub farmer_ata: AccountMeta,

        pub farmer_receipt_ata: AccountMeta,

        pub farmer_reward_ata: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for ClaimRewards instruction
    #[derive(Debug, Clone)]
    pub struct ClaimRewardsInstructionAccounts {
        pub farmer: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub reward_mint: Pubkey,

        pub mint: Pubkey,

        pub receipt_mint: Pubkey,

        pub reward_vault: Pubkey,

        pub vault: Pubkey,

        pub farmer_ata: Pubkey,

        pub farmer_receipt_ata: Pubkey,

        pub farmer_reward_ata: Pubkey,
    }

    impl ClaimRewardsInstructionAccounts {
        pub fn new(
            farmer: Pubkey,

            config: Pubkey,

            market: Pubkey,

            reward_mint: Pubkey,

            mint: Pubkey,

            receipt_mint: Pubkey,

            reward_vault: Pubkey,

            vault: Pubkey,

            farmer_ata: Pubkey,

            farmer_receipt_ata: Pubkey,

            farmer_reward_ata: Pubkey,
        ) -> Self {
            Self {
                farmer,

                config,

                market,

                reward_mint,

                mint,

                receipt_mint,

                reward_vault,

                vault,

                farmer_ata,

                farmer_receipt_ata,

                farmer_reward_ata,
            }
        }
    }

    /// Instruction data for ClaimRewards
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimRewardsInstructionData {}

    impl ClaimRewardsInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ClaimRewardsInstruction
    impl ClaimRewardsInstruction {
        fn discriminator() -> [u8; 8] {
            [4u8, 144u8, 132u8, 71u8, 116u8, 23u8, 151u8, 80u8]
        }

        pub fn data(data: ClaimRewardsInstructionData) -> Self {
            Self {
                accounts: ClaimRewardsInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimRewardsInstructionAccounts) -> Self {
            self.accounts.farmer = AccountMeta::new(accounts.farmer, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.market = AccountMeta::new(accounts.market, false);

            self.accounts.reward_mint = AccountMeta::new_readonly(accounts.reward_mint, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.receipt_mint = AccountMeta::new(accounts.receipt_mint, false);

            self.accounts.reward_vault = AccountMeta::new(accounts.reward_vault, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.farmer_ata = AccountMeta::new(accounts.farmer_ata, false);

            self.accounts.farmer_receipt_ata = AccountMeta::new(accounts.farmer_receipt_ata, false);

            self.accounts.farmer_reward_ata = AccountMeta::new(accounts.farmer_reward_ata, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.farmer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.reward_mint.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.receipt_mint.clone());

            metas.push(self.accounts.reward_vault.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.farmer_ata.clone());

            metas.push(self.accounts.farmer_receipt_ata.clone());

            metas.push(self.accounts.farmer_reward_ata.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateMarket
    // ....................................................................

    /// Main instruction struct for CreateMarket
    pub struct CreateMarketInstruction {
        pub accounts: CreateMarketInstructionAccountMetas,
        pub data: CreateMarketInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateMarket instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateMarketInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub mint: AccountMeta,

        pub vault: AccountMeta,

        pub receipt_mint: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateMarket instruction
    #[derive(Debug, Clone)]
    pub struct CreateMarketInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub mint: Pubkey,

        pub vault: Pubkey,

        pub receipt_mint: Pubkey,
    }

    impl CreateMarketInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            market: Pubkey,

            mint: Pubkey,

            vault: Pubkey,

            receipt_mint: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                market,

                mint,

                vault,

                receipt_mint,
            }
        }
    }

    /// Instruction data for CreateMarket
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateMarketInstructionData {}

    impl CreateMarketInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CreateMarketInstruction
    impl CreateMarketInstruction {
        fn discriminator() -> [u8; 8] {
            [103u8, 226u8, 97u8, 235u8, 200u8, 188u8, 251u8, 254u8]
        }

        pub fn data(data: CreateMarketInstructionData) -> Self {
            Self {
                accounts: CreateMarketInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateMarketInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new(accounts.market, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.receipt_mint = AccountMeta::new(accounts.receipt_mint, true);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.receipt_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Deposit
    // ....................................................................

    /// Main instruction struct for Deposit
    pub struct DepositInstruction {
        pub accounts: DepositInstructionAccountMetas,
        pub data: DepositInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Deposit instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositInstructionAccountMetas {
        pub farmer: AccountMeta,

        pub market: AccountMeta,

        pub mint: AccountMeta,

        pub farmer_ata: AccountMeta,

        pub vault: AccountMeta,

        pub receipt_mint: AccountMeta,

        pub farmer_receipt_ata: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Deposit instruction
    #[derive(Debug, Clone)]
    pub struct DepositInstructionAccounts {
        pub farmer: Pubkey,

        pub market: Pubkey,

        pub mint: Pubkey,

        pub farmer_ata: Pubkey,

        pub vault: Pubkey,

        pub receipt_mint: Pubkey,

        pub farmer_receipt_ata: Pubkey,
    }

    impl DepositInstructionAccounts {
        pub fn new(
            farmer: Pubkey,

            market: Pubkey,

            mint: Pubkey,

            farmer_ata: Pubkey,

            vault: Pubkey,

            receipt_mint: Pubkey,

            farmer_receipt_ata: Pubkey,
        ) -> Self {
            Self {
                farmer,

                market,

                mint,

                farmer_ata,

                vault,

                receipt_mint,

                farmer_receipt_ata,
            }
        }
    }

    /// Instruction data for Deposit
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositInstructionData {
        pub amount: u64,
    }

    impl DepositInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for DepositInstruction
    impl DepositInstruction {
        fn discriminator() -> [u8; 8] {
            [242u8, 35u8, 198u8, 137u8, 82u8, 225u8, 242u8, 182u8]
        }

        pub fn data(data: DepositInstructionData) -> Self {
            Self {
                accounts: DepositInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositInstructionAccounts) -> Self {
            self.accounts.farmer = AccountMeta::new(accounts.farmer, true);

            self.accounts.market = AccountMeta::new(accounts.market, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.farmer_ata = AccountMeta::new(accounts.farmer_ata, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.receipt_mint = AccountMeta::new(accounts.receipt_mint, false);

            self.accounts.farmer_receipt_ata = AccountMeta::new(accounts.farmer_receipt_ata, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.farmer.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.farmer_ata.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.receipt_mint.clone());

            metas.push(self.accounts.farmer_receipt_ata.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub reward_mint: AccountMeta,

        pub authority_ata: AccountMeta,

        pub reward_vault: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub reward_mint: Pubkey,

        pub authority_ata: Pubkey,

        pub reward_vault: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            reward_mint: Pubkey,

            authority_ata: Pubkey,

            reward_vault: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                reward_mint,

                authority_ata,

                reward_vault,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub reward_amount: u64,

        pub fee_bps: u16,
    }

    impl InitializeInstructionData {
        pub fn new(reward_amount: u64, fee_bps: u16) -> Self {
            Self {
                reward_amount,

                fee_bps,
            }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.reward_mint = AccountMeta::new_readonly(accounts.reward_mint, false);

            self.accounts.authority_ata = AccountMeta::new(accounts.authority_ata, false);

            self.accounts.reward_vault = AccountMeta::new(accounts.reward_vault, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.reward_mint.clone());

            metas.push(self.accounts.authority_ata.clone());

            metas.push(self.accounts.reward_vault.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Withdraw
    // ....................................................................

    /// Main instruction struct for Withdraw
    pub struct WithdrawInstruction {
        pub accounts: WithdrawInstructionAccountMetas,
        pub data: WithdrawInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Withdraw instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawInstructionAccountMetas {
        pub farmer: AccountMeta,

        pub market: AccountMeta,

        pub mint: AccountMeta,

        pub receipt_mint: AccountMeta,

        pub vault: AccountMeta,

        pub farmer_ata: AccountMeta,

        pub farmer_receipt_ata: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Withdraw instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawInstructionAccounts {
        pub farmer: Pubkey,

        pub market: Pubkey,

        pub mint: Pubkey,

        pub receipt_mint: Pubkey,

        pub vault: Pubkey,

        pub farmer_ata: Pubkey,

        pub farmer_receipt_ata: Pubkey,
    }

    impl WithdrawInstructionAccounts {
        pub fn new(
            farmer: Pubkey,

            market: Pubkey,

            mint: Pubkey,

            receipt_mint: Pubkey,

            vault: Pubkey,

            farmer_ata: Pubkey,

            farmer_receipt_ata: Pubkey,
        ) -> Self {
            Self {
                farmer,

                market,

                mint,

                receipt_mint,

                vault,

                farmer_ata,

                farmer_receipt_ata,
            }
        }
    }

    /// Instruction data for Withdraw
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawInstructionData {
        pub amount: u64,
    }

    impl WithdrawInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for WithdrawInstruction
    impl WithdrawInstruction {
        fn discriminator() -> [u8; 8] {
            [183u8, 18u8, 70u8, 156u8, 148u8, 109u8, 161u8, 34u8]
        }

        pub fn data(data: WithdrawInstructionData) -> Self {
            Self {
                accounts: WithdrawInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawInstructionAccounts) -> Self {
            self.accounts.farmer = AccountMeta::new(accounts.farmer, true);

            self.accounts.market = AccountMeta::new(accounts.market, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.receipt_mint = AccountMeta::new(accounts.receipt_mint, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.farmer_ata = AccountMeta::new(accounts.farmer_ata, false);

            self.accounts.farmer_receipt_ata = AccountMeta::new(accounts.farmer_receipt_ata, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.farmer.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.receipt_mint.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.farmer_ata.clone());

            metas.push(self.accounts.farmer_receipt_ata.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: Config
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Config {
    pub authority: Pubkey,

    pub reward_mint: Pubkey,

    pub reward_amount: u64,

    pub total_claimed: u64,

    pub fee_bps: u16,

    pub winner_settled: bool,

    pub bump_reward_vault: u8,

    pub bump: u8,
}

impl Config {
    pub fn new(
        authority: Pubkey,

        reward_mint: Pubkey,

        reward_amount: u64,

        total_claimed: u64,

        fee_bps: u16,

        winner_settled: bool,

        bump_reward_vault: u8,

        bump: u8,
    ) -> Self {
        Self {
            authority,

            reward_mint,

            reward_amount,

            total_claimed,

            fee_bps,

            winner_settled,

            bump_reward_vault,

            bump,
        }
    }
}

/// Custom struct: Market
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Market {
    pub mint: Pubkey,

    pub receipt_mint: Pubkey,

    pub total_deposited: u64,

    pub total_claimed: u64,

    pub collected_fees: u64,

    pub fee_bps: u16,

    pub fees_claimed: bool,

    pub status: MarketStatus,

    pub bump_vault: u8,

    pub bump: u8,
}

impl Market {
    pub fn new(
        mint: Pubkey,

        receipt_mint: Pubkey,

        total_deposited: u64,

        total_claimed: u64,

        collected_fees: u64,

        fee_bps: u16,

        fees_claimed: bool,

        status: MarketStatus,

        bump_vault: u8,

        bump: u8,
    ) -> Self {
        Self {
            mint,

            receipt_mint,

            total_deposited,

            total_claimed,

            collected_fees,

            fee_bps,

            fees_claimed,

            status,

            bump_vault,

            bump,
        }
    }
}

/// Custom enum: MarketStatus
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum MarketStatus {
    Open,

    Finalist,

    Loser,

    Winner,
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
